<?php

namespace ContainerTUkOCnE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSummaryAllScoreCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Commands\SummaryAllScoreCommand' shared autowired service.
     *
     * @return \App\Commands\SummaryAllScoreCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Commands/SummaryAllScoreCommand.php';

        $container->privates['App\\Commands\\SummaryAllScoreCommand'] = $instance = new \App\Commands\SummaryAllScoreCommand(($container->privates['App\\Repository\\UsersRepository'] ?? $container->load('getUsersRepositoryService')));

        $instance->setName('score:all');

        return $instance;
    }
}
