<?php

namespace ContainerTUkOCnE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sCVTKmN.App\Controller\UsersController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sCVTKmN.App\\Controller\\UsersController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'users' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'users' => 'App\\Repository\\UsersRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\UsersController::index()', $container);
    }
}
