<?php

namespace ContainerEtuqh6a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetScoreUserByIdCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Commands\GetScoreUserByIdCommand' shared autowired service.
     *
     * @return \App\Commands\GetScoreUserByIdCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Commands/GetScoreUserByIdCommand.php';

        $container->privates['App\\Commands\\GetScoreUserByIdCommand'] = $instance = new \App\Commands\GetScoreUserByIdCommand(($container->privates['App\\Repository\\UsersRepository'] ?? $container->load('getUsersRepositoryService')));

        $instance->setName('score:id');

        return $instance;
    }
}
