<?php

namespace ContainerEtuqh6a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllershowService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.M..mpr4.App\Controller\UsersController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M..mpr4.App\\Controller\\UsersController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.M..mpr4.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.M..mpr4": it needs an instance of "App\\Entity\\Users" but this type has been excluded in "config/services.yaml".'],
        ], [
            'user' => 'App\\Entity\\Users',
        ]))->withContext('App\\Controller\\UsersController::show()', $container);
    }
}
