<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEtuqh6a\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEtuqh6a/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerEtuqh6a.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerEtuqh6a\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerEtuqh6a\App_KernelTestDebugContainer([
    'container.build_hash' => 'Etuqh6a',
    'container.build_id' => '2aa0bd49',
    'container.build_time' => 1745764319,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEtuqh6a');
